-- MySQL Script generated by MySQL Workbench
-- Tue Mar 23 17:43:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjectManagementSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjectManagementSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjectManagementSystem` DEFAULT CHARACTER SET utf8 ;
USE `ProjectManagementSystem` ;

-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`project_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`project_manager` (
  `project_manager_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_manager_code` VARCHAR(15) NOT NULL,
  `project_manager_name` VARCHAR(50) NOT NULL,
  `project_manager_email` VARCHAR(30) NOT NULL,
  `project_manager_username` VARCHAR(30) NOT NULL,
  `project_manager_password` VARCHAR(30) NOT NULL,
  `project_manager_salary` FLOAT(11) NOT NULL,
  `stake_holders_primary_sh_name` VARCHAR(20) NOT NULL,
  `project_updates_1_update_id` INT(11) NOT NULL,
  `project_updates_1_company_company_id` INT(11) NOT NULL,
  PRIMARY KEY (`project_manager_id`, `stake_holders_primary_sh_name`, `project_updates_1_update_id`, `project_updates_1_company_company_id`),
  INDEX `fk_project_manager_stake_holders1_idx` (`stake_holders_primary_sh_name` ASC) VISIBLE,
  INDEX `fk_project_manager_project_updates_11_idx` (`project_updates_1_update_id` ASC, `project_updates_1_company_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_manager_stake_holders1`
    FOREIGN KEY (`stake_holders_primary_sh_name`)
    REFERENCES `ProjectManagementSystem`.`stake_holders` (`primary_sh_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_manager_project_updates_11`
    FOREIGN KEY (`project_updates_1_update_id` , `project_updates_1_company_company_id`)
    REFERENCES `ProjectManagementSystem`.`project_updates_corporate` (`update_id` , `company_company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`project` (
  `project_id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NOT NULL,
  `project_name` VARCHAR(50) NOT NULL,
  `project_code` VARCHAR(15) NOT NULL,
  `project_description` VARCHAR(100) NOT NULL,
  `project_manager_id` INT(11) NOT NULL,
  `project_budget` FLOAT(11) NOT NULL,
  `project_start_date` DATE NOT NULL,
  `project_end_date` DATE NOT NULL,
  `project_bulletin_board` VARCHAR(30) NOT NULL,
  `project_build_location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX (`project_manager_id` ASC) VISIBLE,
  INDEX (`company_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`project_manager_id`)
    REFERENCES `ProjectManagementSystem`.`project_manager` (`project_manager_id`),
  CONSTRAINT ``
    FOREIGN KEY (`company_id`)
    REFERENCES `ProjectManagementSystem`.`company` (`company_id`));


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`project_updates_corporate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`project_updates_corporate` (
  `update_id` INT(11) NOT NULL AUTO_INCREMENT,
  `update_code` VARCHAR(15) NOT NULL,
  `date_of_update` DATE NOT NULL,
  `project_id` INT(11) NULL,
  `project_member_id` INT(11) NULL,
  `hours_contributed`  NULL,
  `company_company_id` INT(11) NOT NULL,
  `project_project_id` INT(11) NOT NULL,
  PRIMARY KEY (`update_id`, `company_company_id`),
  INDEX `fk_project_updates_1_company1_idx` (`company_company_id` ASC) VISIBLE,
  INDEX `fk_project_updates_1_project1_idx` (`project_project_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_updates_1_company1`
    FOREIGN KEY (`company_company_id`)
    REFERENCES `ProjectManagementSystem`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_updates_1_project1`
    FOREIGN KEY (`project_project_id`)
    REFERENCES `ProjectManagementSystem`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`stake_holders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`stake_holders` (
  `primary_sh_name` VARCHAR(20) NOT NULL,
  `primary_sh_sponsors` INT(11) NOT NULL,
  `sh_ID` INT(11) NOT NULL,
  `reqrements_update` DATE NOT NULL,
  `sh_budget` FLOAT(32) NOT NULL,
  `company_email`  NULL,
  `project_id`  NULL,
  `project_member_id`  NULL,
  `project_updates_1_update_id` INT(11) NOT NULL,
  PRIMARY KEY (`primary_sh_name`),
  INDEX `fk_stake_holders_project_updates_11_idx` (`project_updates_1_update_id` ASC) VISIBLE,
  CONSTRAINT `fk_stake_holders_project_updates_11`
    FOREIGN KEY (`project_updates_1_update_id`)
    REFERENCES `ProjectManagementSystem`.`project_updates_corporate` (`update_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`company` (
  `company_id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(30) NOT NULL,
  `company_email` VARCHAR(30) NOT NULL,
  `company_username` VARCHAR(30) NOT NULL,
  `company_password` VARCHAR(30) NOT NULL,
  `stake_holders_primary_sh_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`company_id`),
  INDEX `fk_company_stake_holders1_idx` (`stake_holders_primary_sh_name` ASC) VISIBLE,
  CONSTRAINT `fk_company_stake_holders1`
    FOREIGN KEY (`stake_holders_primary_sh_name`)
    REFERENCES `ProjectManagementSystem`.`stake_holders` (`primary_sh_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`supervisor` (
  `supervisor_master_id` INT(11) NOT NULL AUTO_INCREMENT,
  `supervisor_id` INT(11) NOT NULL,
  `supervisor_code` VARCHAR(15) NOT NULL,
  `supervisor_name` VARCHAR(50) NOT NULL,
  `supervisor_email` VARCHAR(30) NOT NULL,
  `supervisor_username` VARCHAR(30) NOT NULL,
  `supervisor_password` VARCHAR(30) NOT NULL,
  `supervisor_salary` VARCHAR(11) NOT NULL,
  `timestamps_project_updates_employee_update_id` INT(11) NOT NULL,
  `timestamps_project_updates_employee_employees_employee_SSN` INT(9) NOT NULL,
  `timestamps_project_updates_employee_employees_project_project_id` INT(11) NOT NULL,
  `timestamps_project_updates_employee_employees_supervisor_supervisor_master_id` INT(11) NOT NULL,
  `timestamps_project_updates_employee_supervisor_supervisor_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`supervisor_master_id`),
  INDEX `fk_supervisor_timestamps1_idx` (`timestamps_project_updates_employee_update_id` ASC, `timestamps_project_updates_employee_employees_employee_SSN` ASC, `timestamps_project_updates_employee_employees_project_project_id` ASC, `timestamps_project_updates_employee_employees_supervisor_supervisor_master_id` ASC, `timestamps_project_updates_employee_supervisor_supervisor_master_id` ASC) VISIBLE,
  CONSTRAINT `fk_supervisor_timestamps1`
    FOREIGN KEY (`timestamps_project_updates_employee_update_id` , `timestamps_project_updates_employee_employees_employee_SSN` , `timestamps_project_updates_employee_employees_project_project_id` , `timestamps_project_updates_employee_employees_supervisor_supervisor_master_id` , `timestamps_project_updates_employee_supervisor_supervisor_master_id`)
    REFERENCES `ProjectManagementSystem`.`timestamps` (`project_updates_employee_update_id` , `project_updates_employee_employees_employee_SSN` , `project_updates_employee_employees_project_project_id` , `project_updates_employee_employees_supervisor_supervisor_master_id` , `project_updates_employee_supervisor_supervisor_master_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`employees` (
  `employee_SSN` INT(9) NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(50) NOT NULL,
  `employee_salary` FLOAT(11) NOT NULL,
  `employee_DOB` DATE NOT NULL,
  `employee_current_address` VARCHAR(15) NOT NULL,
  `employee_contact_number` INT(11) NOT NULL,
  `project_project_id` INT(11) NOT NULL,
  `supervisor_supervisor_master_id` INT(11) NOT NULL,
  `company_company_id` INT(11) NOT NULL,
  PRIMARY KEY (`employee_SSN`, `project_project_id`, `supervisor_supervisor_master_id`),
  INDEX `fk_employees_project1_idx` (`project_project_id` ASC) VISIBLE,
  INDEX `fk_employees_supervisor1_idx` (`supervisor_supervisor_master_id` ASC) VISIBLE,
  INDEX `fk_employees_company1_idx` (`company_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_project1`
    FOREIGN KEY (`project_project_id`)
    REFERENCES `ProjectManagementSystem`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_supervisor1`
    FOREIGN KEY (`supervisor_supervisor_master_id`)
    REFERENCES `ProjectManagementSystem`.`supervisor` (`supervisor_master_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_company1`
    FOREIGN KEY (`company_company_id`)
    REFERENCES `ProjectManagementSystem`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`project_updates_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`project_updates_employee` (
  `update_id` INT(11) NOT NULL AUTO_INCREMENT,
  `update_code` VARCHAR(15) NOT NULL,
  `date_of_update` DATE NOT NULL,
  `project_id` INT(11) NOT NULL,
  `project_member_id` INT(11) NULL DEFAULT NULL,
  `hours_contributed` FLOAT(11) NULL DEFAULT NULL,
  `employees_employee_SSN` INT(9) NOT NULL,
  `employees_project_project_id` INT(11) NOT NULL,
  `employees_supervisor_supervisor_master_id` INT(11) NOT NULL,
  `supervisor_supervisor_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`update_id`, `employees_employee_SSN`, `employees_project_project_id`, `employees_supervisor_supervisor_master_id`, `supervisor_supervisor_master_id`),
  INDEX (`project_id` ASC) VISIBLE,
  INDEX (`project_member_id` ASC) VISIBLE,
  INDEX `fk_project_updates_employees1_idx` (`employees_employee_SSN` ASC, `employees_project_project_id` ASC, `employees_supervisor_supervisor_master_id` ASC) VISIBLE,
  INDEX `fk_project_updates_supervisor1_idx` (`supervisor_supervisor_master_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`project_id`)
    REFERENCES `ProjectManagementSystem`.`project` (`project_id`),
  CONSTRAINT ``
    FOREIGN KEY (`project_member_id`)
    REFERENCES `ProjectManagementSystem`.`project_member` (`project_member_id`),
  CONSTRAINT `fk_project_updates_employees1`
    FOREIGN KEY (`employees_employee_SSN` , `employees_project_project_id` , `employees_supervisor_supervisor_master_id`)
    REFERENCES `ProjectManagementSystem`.`employees` (`employee_SSN` , `project_project_id` , `supervisor_supervisor_master_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_updates_supervisor1`
    FOREIGN KEY (`supervisor_supervisor_master_id`)
    REFERENCES `ProjectManagementSystem`.`supervisor` (`supervisor_master_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `project_updates_employee_update_id` INT(11) NOT NULL,
  `project_updates_employee_employees_employee_SSN` INT(9) NOT NULL,
  `project_updates_employee_employees_project_project_id` INT(11) NOT NULL,
  `project_updates_employee_employees_supervisor_supervisor_master_id` INT(11) NOT NULL,
  `project_updates_employee_supervisor_supervisor_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`project_updates_employee_update_id`, `project_updates_employee_employees_employee_SSN`, `project_updates_employee_employees_project_project_id`, `project_updates_employee_employees_supervisor_supervisor_master_id`, `project_updates_employee_supervisor_supervisor_master_id`),
  CONSTRAINT `fk_timestamps_project_updates_employee1`
    FOREIGN KEY (`project_updates_employee_update_id` , `project_updates_employee_employees_employee_SSN` , `project_updates_employee_employees_project_project_id` , `project_updates_employee_employees_supervisor_supervisor_master_id` , `project_updates_employee_supervisor_supervisor_master_id`)
    REFERENCES `ProjectManagementSystem`.`project_updates_employee` (`update_id` , `employees_employee_SSN` , `employees_project_project_id` , `employees_supervisor_supervisor_master_id` , `supervisor_supervisor_master_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`project_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`project_member` (
  `project_member_id` INT(11) NOT NULL,
  `project_member_code` VARCHAR(15) NOT NULL,
  `project_member_name` VARCHAR(50) NOT NULL,
  `project_member_email` VARCHAR(30) NOT NULL,
  `project_member_username` VARCHAR(30) NOT NULL,
  `project_member_password` VARCHAR(30) NOT NULL,
  `project_member_salary` FLOAT(11) NOT NULL,
  `project_member_headcount` INT(50) NOT NULL AUTO_INCREMENT,
  `timestamps_project_updates_employee_update_id` INT(11) NOT NULL,
  `timestamps_project_updates_employee_employees_employee_SSN` INT(9) NOT NULL,
  `timestamps_project_updates_employee_employees_project_project_id` INT(11) NOT NULL,
  `timestamps_project_updates_employee_employees_supervisor_supervisor_master_id` INT(11) NOT NULL,
  `timestamps_project_updates_employee_supervisor_supervisor_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`project_member_id`),
  INDEX `fk_project_member_timestamps1_idx` (`timestamps_project_updates_employee_update_id` ASC, `timestamps_project_updates_employee_employees_employee_SSN` ASC, `timestamps_project_updates_employee_employees_project_project_id` ASC, `timestamps_project_updates_employee_employees_supervisor_supervisor_master_id` ASC, `timestamps_project_updates_employee_supervisor_supervisor_master_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_member_timestamps1`
    FOREIGN KEY (`timestamps_project_updates_employee_update_id` , `timestamps_project_updates_employee_employees_employee_SSN` , `timestamps_project_updates_employee_employees_project_project_id` , `timestamps_project_updates_employee_employees_supervisor_supervisor_master_id` , `timestamps_project_updates_employee_supervisor_supervisor_master_id`)
    REFERENCES `ProjectManagementSystem`.`timestamps` (`project_updates_employee_update_id` , `project_updates_employee_employees_employee_SSN` , `project_updates_employee_employees_project_project_id` , `project_updates_employee_employees_supervisor_supervisor_master_id` , `project_updates_employee_supervisor_supervisor_master_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`tasks` (
  `project_update` DATE NOT NULL,
  `project_skill_ID` INT(9) NOT NULL,
  `project_subtasks` VARCHAR(30) NULL,
  `project_schedule_update` DATE NOT NULL,
  `project_task_budget_initial` FLOAT(11) NOT NULL,
  `project_schedule_start_date` DATE NOT NULL,
  `project_schedule_end_date` DATE NOT NULL,
  `project_task_budget_actual` FLOAT(11) NOT NULL,
  `project_headcount` INT(9) NOT NULL,
  `project_project_id` INT(11) NOT NULL,
  PRIMARY KEY (`project_project_id`),
  CONSTRAINT `fk_tasks_project1`
    FOREIGN KEY (`project_project_id`)
    REFERENCES `ProjectManagementSystem`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`project_member_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`project_member_assignment` (
  `project_member_id` INT(11) NOT NULL,
  `tasks_project_project_id` INT(11) NOT NULL,
  INDEX (`project_member_id` ASC) VISIBLE,
  INDEX `fk_project_member_assignment_tasks1_idx` (`tasks_project_project_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`project_member_id`)
    REFERENCES `ProjectManagementSystem`.`project_member` (`project_member_id`),
  CONSTRAINT `fk_project_member_assignment_tasks1`
    FOREIGN KEY (`tasks_project_project_id`)
    REFERENCES `ProjectManagementSystem`.`tasks` (`project_project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ProjectManagementSystem`.`build_timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectManagementSystem`.`build_timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `employees_employee_SSN` INT(9) NOT NULL,
  `employees_project_project_id` INT(11) NOT NULL,
  `employees_supervisor_supervisor_master_id` INT(11) NOT NULL,
  `project_project_id` INT(11) NOT NULL,
  `project_manager_project_manager_id` INT(11) NOT NULL,
  `project_manager_stake_holders_primary_sh_name` VARCHAR(20) NOT NULL,
  `project_manager_project_updates_1_update_id` INT(11) NOT NULL,
  `project_manager_project_updates_1_company_company_id` INT(11) NOT NULL,
  PRIMARY KEY (`employees_employee_SSN`, `employees_project_project_id`, `employees_supervisor_supervisor_master_id`, `project_project_id`, `project_manager_project_manager_id`, `project_manager_stake_holders_primary_sh_name`, `project_manager_project_updates_1_update_id`, `project_manager_project_updates_1_company_company_id`),
  INDEX `fk_timestamps_project1_idx` (`project_project_id` ASC) VISIBLE,
  INDEX `fk_timestamps_project_manager1_idx` (`project_manager_project_manager_id` ASC, `project_manager_stake_holders_primary_sh_name` ASC, `project_manager_project_updates_1_update_id` ASC, `project_manager_project_updates_1_company_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_timestamps_employees1`
    FOREIGN KEY (`employees_employee_SSN` , `employees_project_project_id` , `employees_supervisor_supervisor_master_id`)
    REFERENCES `ProjectManagementSystem`.`employees` (`employee_SSN` , `project_project_id` , `supervisor_supervisor_master_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timestamps_project1`
    FOREIGN KEY (`project_project_id`)
    REFERENCES `ProjectManagementSystem`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timestamps_project_manager1`
    FOREIGN KEY (`project_manager_project_manager_id` , `project_manager_stake_holders_primary_sh_name` , `project_manager_project_updates_1_update_id` , `project_manager_project_updates_1_company_company_id`)
    REFERENCES `ProjectManagementSystem`.`project_manager` (`project_manager_id` , `stake_holders_primary_sh_name` , `project_updates_1_update_id` , `project_updates_1_company_company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
